### ISSUE TITLE
Area Code is already set.

### ISSUE THREAD

**Issue by vipul-evrig** [klaviyo/magento2-klaviyo#296] opened 2024-05-10 11:16 UTC
### Environment details

PHP version: 8.1.25
Magento version: 2.4.5-p7
Klaviyo extension version: 4.1.0
Anything else that would help a developer reproduce the bug?

### Steps to reproduce

Hi,

Error : area code is already set when we run consumers queue command on terminal.

eg. php n98-magerun2.phar queue:consumers:start exportProcessor

It will give the error from bellow code - 

Path: vendor/klaviyo/magento2-extension/Helper/ScopeSetting.php
Line no: 63
Code: $this->_state->setAreaCode(\Magento\Framework\App\Area::AREA_ADMINHTML);

Please look into this and provide solution as soon as possible.
![Screenshot from 2024-05-10 10-41-56](https://github.com/klaviyo/magento2-klaviyo/assets/108509982/51c85a23-1895-4339-8ede-f8d425782980)

### Expected result

It should properly working with consumer queue.

### Actual result

Error : area code is already set when we run consumers queue command on terminal.

eg. php n98-magerun2.phar queue:consumers:start exportProcessor

It will give the error from bellow code - 

Path: vendor/klaviyo/magento2-extension/Helper/ScopeSetting.php
Line no: 63
Code: $this->_state->setAreaCode(\Magento\Framework\App\Area::AREA_ADMINHTML);

Please look into this and provide solution as soon as possible.

**Comment by kamidzi-klaviyo-integrations** [comment] 2024-05-13 19:34
@vipul-evrig  - I am not able to reproduce this. Do you have something specific in your configurations that may assist in reproducing? Could you post the output of running `queue:consumers:start` with `-vvv` flag?

**Comment by vipul-evrig** [comment] 2024-05-14 08:58
Hello Sir,

I have attached a log file as per your request. 

Also I have attached a video on how to reproduce the issue for this.

Please look into this and provide a solution as soon as possible.

https://github.com/klaviyo/magento2-klaviyo/assets/108509982/1e181d39-bfe4-4cd4-982d-6da7dd0f0c16

[Area-Code-is-already-set-Issue-296-klaviyo-magento2-klaviyo-14may2024.txt](https://github.com/klaviyo/magento2-klaviyo/files/15305880/Area-Code-is-already-set-Issue-296-klaviyo-magento2-klaviyo-14may2024.txt)

**Comment by kamidzi-klaviyo-integrations** [comment] 2024-05-17 20:20
@vipul-evrig  - Just to update you; looking at this, it _does_ appear that there is a method [`checkAreaCode`](https://github.com/klaviyo/magento2-klaviyo/blob/4.1.0/Helper/ScopeSetting.php#L96) which has side-effect of attempting to set the Area Code. We are investigating further.

**Comment by vipul-evrig** [comment] 2024-05-20 05:37
Hello Sir,

Thank you for your replied. 

Please investigating and provide solution.

**Comment by cykolln** [comment] 2024-05-21 21:48
@vipul-evrig Thanks for raising - we are unable to recreate locally on the same version of magento with the same version of klaviyo extension installed. Can you be more specific about what export jobs you are trying to run, this will help us recreate and put out a fix.

**Comment by vipul-evrig** [comment] 2024-05-23 07:25
Hello Dear,

We are using below export job command in terminal. 

php n98-magerun2.phar queue:consumers:start exportProcessor

Also you can try below command
bin/magento queue:consumers:start exportprocessor

Please look into this and provide solution.

Thanks,

**Comment by cykolln** [comment] 2024-05-23 14:27
@vipul-evrig I understand that you are trying to run the export job command. However running the same command we are unable to recreate unless we know what specific resources are being exported. Please respond with which entity type you are trying to export: 
![image](https://github.com/klaviyo/magento2-klaviyo/assets/78871498/47be7b98-cd18-42dc-a2be-8dbce02cd5e2)

**Comment by cykolln** [comment] 2024-09-25 14:19
This should be fixed in version 4.2.0!

**Closed by cykolln** 2024-09-25 14:19 UTC
Labels: internal-bug-created, unable-to-recreate
