### ISSUE TITLE
Klaviyo blocks checkout from working - error with method getKlSmsConsent()

### ISSUE THREAD

**Issue by RoboSowo** [klaviyo/magento2-klaviyo#191] opened 2022-05-24 11:29 UTC
We are in the process of installing Klaviyo to our Magento2, but before even configuring the app, we can see that the app is preventing our checkout flow in functioning. We get following error message: 

main.CRITICAL: Error: Call to undefined method Magento\Checkout\Api\Data\ShippingInformationExtension::getKlSmsConsent() in /home/web/OURSITE/releases/20220523065500/vendor/klaviyo/magento2-extension/model/Checkout/ShippingInformationManagement.php:29

Does anyone experience something similar and do you have a fix for it?

We previously installed Klaviyo to our test site, and that worked as expected. We have done exactly same steps so far.

Br Sophie

**Comment by VivekShingala** [comment] 2022-10-04 21:58
Hi @RoboSowo 

We are also experiencing the same issue. Our staging site is working fine, but it is breaking the production site checkout page with the error you have mentioned.

We have same Magento, PHP and Klaviyo versions for our staging and production environment. Could you please help me if you have already fixed this issue?

**Comment by RoboSowo** [comment] 2022-10-05 05:07
No, we did not find a fix, so we had to install an older version of the
application...

Do you plan to make a solution in this in the near future?

Br Sophie

**Comment by VivekShingala** [comment] 2022-10-05 05:18
Oh, I see.

Yes, I am working on it to find and fix the issue. Will let you know here.

**Comment by cykolln** [comment] 2022-10-06 23:41
Thank you for raising this - I've created an internal ticket to investigate this and will update this issue when it gets picked up.

**Comment by cykolln** [comment] 2022-10-06 23:42
@RoboSowo @VivekShingala can you please share which version of Magento you're using?

**Comment by VivekShingala** [comment] 2022-10-07 01:57
Hi @cykolln 

I'm using below versions for my website:

Magento: 2.4.3-p2
PHP: 7.4.12
Klaviyo: 4.0.5

Please note that we have the same configuration for our staging site as well and it's working correctly. The issue we are facing is on production server.

**Comment by cykolln** [comment] 2022-10-07 15:10
Hi @VivekShingala - thanks for supplying your configuration for us. A lot of the time issues with extension attributes can be resolved by removing the /generated directory and recompiling:

```
rm -rf generated/*
php bin/magento setup:di:compile
```

**Comment by VivekShingala** [comment] 2022-10-07 15:55
Hi @cykolln 

We are using deployer so generated folder is newly created each time we deploy the code to the server. So, that can't be the issue.

**Closed** 2023-04-11 17:35 UTC
Labels: internal-bug-created

**Comment by wmdkdkussin** [comment] 2023-07-14 08:48
FYI: We still experience the issue with KLYVIYO v4.0.11 and Magento v2.4.2-p2.

**Comment by jtomka** [comment] 2023-08-25 01:47
Confirming the issue is present in Magento 2.4.5-p1 and Klaviyo_Reclaim 4.0.12.

However, the issue seems to be with Deployer and its Magento 2 recipe. I haven't had a chance to investigate in depth, but re-deploying resolves the issue. I suspect it's the order of steps in Deployer recipe that makes it require two consecutive deployments for the newly installed extension to work.

In short, redeploy and see if it helps.
