### ISSUE TITLE
ReferenceError: Can't find variable: _learnq

### ISSUE THREAD

**Issue by clivewalkden** [klaviyo/magento2-klaviyo#47] opened 2019-08-17 19:25 UTC
Hi,

I'm getting this on latest 1.1.2 version and Magento 2.3.2
Reporting about 700 errors on a newly launched site (via Sentry.io) in approximately 48 hours. Happening across multiple browsers and devices.

Same issue reported in reports #16 and #42 I'm not sure what percentage of users are getting this issue.

**Comment by remstone7** [comment] 2019-08-18 21:52
I'm not able to reproduce this on my testing - have tried with M2.1.1 and just did with 2.3.2 -  should have been fixed with #43.  Do you have any repro steps?  I will continue to look into this...

**Comment by remstone7** [comment] 2019-08-29 11:20
addressed again in #46

**Closed by remstone7** 2019-08-29 11:20 UTC

**Comment by clivewalkden** [comment] 2020-01-23 08:43
@remstone7 sorry to take so long to get back, this is caused by uBlock Origin blocking the https://static.klaviyo.com/onsite/js/klaviyo.js file being loaded. Can there be some check on the _learnq variable to stop this error appearing in the console and causing knock on issues on the page due to the JS error?

**Comment by remstone7** [comment] 2020-01-23 12:32
yea so we should be doing something like:

`var _learnq = _learnq || [];` which would remove this from happening.. 
https://github.com/klaviyo/magento2-klaviyo/blob/3a1ddde65896304f2c087f1f69d6fba194434648/view/frontend/templates/product/viewed.phtml#L7
https://github.com/klaviyo/magento2-klaviyo/blob/3a1ddde65896304f2c087f1f69d6fba194434648/view/frontend/web/js/customer.js#L8
https://github.com/klaviyo/magento2-klaviyo/blob/71a485a0b658bb4f54f2489fbde86901fd111b7c/view/frontend/web/js/view/checkout/email.js#L33

this should cover it.. this is resolved based on the above, are you on the updated versions?

**Comment by clivewalkden** [comment] 2020-01-31 09:15
@remstone7 I'll get the latest version installed and confirm
