### ISSUE TITLE
Cannot save Theme Configuration

### ISSUE THREAD

**Issue by iangoh414** [klaviyo/magento2-klaviyo#2] opened 2017-03-09 05:27 UTC
Content->Configuration-> Edit (Theme) ->Save Configuration, you will get an error.

Something went wrong while saving this configuration: Notice: Undefined index: field in /home/vocando/public_html/store/vendor/klaviyo/magento2-extension/Observer/PrivateApiKeyObserver.php on line 25

Please fix this ASAP

**Comment by henry-chan-klaviyo** [comment] 2017-03-09 15:12
This is a duplicate of https://github.com/klaviyo/magento2-klaviyo/issues/1

**Closed by henry-chan-klaviyo** 2017-03-09 15:12 UTC
